# Generated by Django 3.1.1 on 2020-09-18 17:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('crm', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text="Phone number must be in the format: '(DDD) 9XXXX-XXXX'. Only numbers", max_length=12)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Hourly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
            ],
            options={
                'verbose_name': 'Hourly',
                'verbose_name_plural': 'Hourlys',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.doctor')),
                ('hourlys', models.ManyToManyField(to='api.Hourly')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduling_date', models.DateTimeField(auto_now=True)),
                ('hourly', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.hourly')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.schedule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.specialty'),
        ),
    ]
